Updates were skipped successfully.
Goodbye!
Бот вышел онлайн.
Подключен к БД
Updates were skipped successfully.
Updates were skipped successfully.
Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Updates were skipped successfully.
Task exception was never retrieved
future: <Task finished name='Task-1196' coro=<Dispatcher._process_polling_updates() done, defined at /home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=UndefinedFunction("operator does not exist: character = timestamp without time zone\nLINE 1: ...                                  ')) WHERE phone = '2022-02...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n")>
Traceback (most recent call last):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/crimgo/.local/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/crimgo/dev/CrimGo/handlers/driver.py", line 30, in validate_driver_otp
    if (await crimgo_db.is_driver_valid(state, message)):
  File "/home/crimgo/dev/CrimGo/database/crimgo_db.py", line 76, in is_driver_valid
    cursor.execute('UPDATE driver SET (telegram_name, telegram_id, timestamp) = (%s, %s, %s) WHERE phone = %s', (message.from_user.username, message.from_user.id, drv_phone, datetime.datetime.now()))
psycopg2.errors.UndefinedFunction: operator does not exist: character = timestamp without time zone
LINE 1: ...                                  ')) WHERE phone = '2022-02...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

Updates were skipped successfully.
